# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default=b'defTitle', max_length=256),
        ),
    ]
