# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_document_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='docfile',
            field=models.FileField(upload_to=b'documents/title'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default=b'defTitle', max_length=256, unique=True),
        ),
    ]
